# Generated by Django 5.2.17 on 2026-08-05 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('listing_type', models.CharField(max_length=10)),
                ('details', models.JSONField(default=dict)),
                ('photos', models.JSONField(default=list)),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('woreda', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('broker_notes', models.TextField(blank=True, null=True)),
                ('owner_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listing_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
