# Generated by Django 5.2.17 on 2026-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_unit', models.CharField(choices=[('SQM', 'Square Metres'), ('HECTARE', 'Hectare')], default='SQM', max_length=10)),
                ('land_use', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('AGRICULTURAL', 'Agricultural'), ('MIXED', 'Mixed Use')], default='RESIDENTIAL', max_length=15)),
                ('has_title_deed', models.BooleanField(default=False)),
                ('road_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'land_details',
            },
        ),
    ]
