# Generated by Django 5.2.17 on 2026-08-05 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('co_broker_split_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
