# Generated by Django 5.2.17 on 2026-08-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('RECONDITIONED', 'Reconditioned')], max_length=15)),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_details', to='listings.listing')),
            ],
            options={
                'db_table': 'machine_details',
            },
        ),
    ]
