# Generated by Django 5.2.17 on 2026-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('STUDIO', 'Studio'), ('OTHER', 'Other')], default='APARTMENT', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'house_details',
            },
        ),
    ]
